all:
	$(MAKE) -f ${CURDIR}/../Makefile.ntscu clean
	$(MAKE) -f ${CURDIR}/../Makefile.pal clean
# 	$(MAKE) -f ${CURDIR}/../Makefile.ntscj clean
	$(MAKE) -f ${CURDIR}/../Makefile.ntscu
	$(MAKE) -f ${CURDIR}/../Makefile.pal
# 	$(MAKE) -f ${CURDIR}/../Makefile.ntscj

clean:
	$(MAKE) -f ${CURDIR}/../Makefile.ntscu clean
	$(MAKE) -f ${CURDIR}/../Makefile.pal clean
# 	$(MAKE) -f ${CURDIR}/../Makefile.ntscj clean
	rm -f *.bin *.elf

