EE_FILE_NAME = test
EE_OBJS = functions.o main.o
ADDRESS = 000b000

EE_OBJS_DIR = obj/
EE_BIN_DIR = bin/
EE_ELF = $(EE_BIN_DIR)$(EE_FILE_NAME).$(EE_REGION).elf
EE_BIN = $(EE_BIN_DIR)$(EE_FILE_NAME).$(EE_REGION).bin

# Define EE_DEFS first
# EE_DEFS += -DDROIDS
# EE_DEFS += -DBOTS
# EE_DEFS += -DCTF
# EE_DEFS += -DSIEGE
# EE_DEFS += -DHUD
# EE_DEFS += -DSCAVENGERHUNT
# EE_DEFS += -DSECRET
# EE_DEFS += -DKOTH
# EE_DEFS += -DJUMPPAD
# EE_DEFS += -DDOMINATION

# Add conditional object files BEFORE the directory prefix transformation
ifneq (,$(findstring -DDROIDS,$(EE_DEFS)))
    EE_OBJS += droids.o
endif
ifneq (,$(findstring -DBOTS,$(EE_DEFS)))
    EE_OBJS += bots.o trainingmode.o
endif
ifneq (,$(findstring -DCTF,$(EE_DEFS)))
    EE_OBJS += ctf.o
endif
ifneq (,$(findstring -DSIEGE,$(EE_DEFS)))
    EE_OBJS += siege.o
endif
ifneq (,$(findstring -DKOTH,$(EE_DEFS)))
    EE_OBJS += koth.o
endif
ifneq (,$(findstring -DSECRET,$(EE_DEFS)))
    EE_OBJS += secret.o
endif
ifneq (,$(findstring -DHUD,$(EE_DEFS)))
    EE_OBJS += hud.o
endif
ifneq (,$(findstring -DSCAVENGERHUNT,$(EE_DEFS)))
    EE_OBJS += scavengerhunt.o
endif
ifneq (,$(findstring -DJUMPPAD,$(EE_DEFS)))
    EE_OBJS += jumppad.o
endif
ifneq (,$(findstring -DDOMINATION,$(EE_DEFS)))
    EE_OBJS += domination.o
endif

# Debug: Print what we have before transformation
$(info Before transform: EE_OBJS = $(EE_OBJS))

# NOW add the obj/ prefix to ALL objects
EE_OBJS := $(EE_OBJS:%=$(EE_OBJS_DIR)%)

# Debug: Print what we have after transformation
$(info After transform: EE_OBJS = $(EE_OBJS))

# Set other variables
EE_INCS := -I../../include -I$(PS2SDK)/ports/include
EE_LDFLAGS = -fno-builtin -nostdlib -nostartfiles -L. -L../../lib -L$(PS2SDK)/ports/lib
EE_CFLAGS := -D_PROGRAM_ENTRY=0x$(ADDRESS) -DDEBUG

# Add debug flag if debug target
ifeq ($(filter debug,$(MAKECMDGOALS)),debug)
    EE_CFLAGS := $(EE_CFLAGS) -DDEBUG
endif

all: linker $(EE_OBJS_DIR) $(EE_BIN_DIR) $(EE_BIN) code

$(EE_OBJS_DIR):
	mkdir -p $(EE_OBJS_DIR)

$(EE_BIN_DIR):
	mkdir -p $(EE_BIN_DIR)

$(EE_OBJS_DIR)%.o : $(EE_SRC_DIR)%.c
	$(EE_C_COMPILE) -c $< -o $@

$(EE_OBJS_DIR)%.o : $(EE_SRC_DIR)%.S
	$(EE_C_COMPILE) -c $< -o $@

linker:
	$(EE_CC) -E -x c $(EE_CFLAGS) ../../linkfile.template | grep -v '^#' > linkfile

code:
	bin2code $(EE_BIN) $(ADDRESS) $(EE_BIN).raw raw
	cat template/footer.$(EE_REGION).raw >> $(EE_BIN).raw
	bin2code $(EE_BIN) $(ADDRESS) $(EE_BIN).pnach pnach
	cat template/footer.$(EE_REGION).pnach >> $(EE_BIN).pnach

clean:
	rm -rf linkfile
	rm -f -r $(EE_OBJS_DIR)
	rm -f -r $(EE_BIN_DIR)

include $(CURDIR)/../../Makefile.pref
include $(CURDIR)/../../Makefile.eeglobal
